<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="1" failures="0" name="fizzbuzz_tests.fizzBuzzTest-20181018155630" skipped="0" tests="18" time="0.003" timestamp="2018-10-18T15:56:30">
	<testcase classname="fizzbuzz_tests.fizzBuzzTest" name="test_if_0_is_0" time="0.000" timestamp="2018-10-18T15:56:30"/>
	<testcase classname="fizzbuzz_tests.fizzBuzzTest" name="test_if_10_is_buzz" time="0.000" timestamp="2018-10-18T15:56:30"/>
	<testcase classname="fizzbuzz_tests.fizzBuzzTest" name="test_if_15_is_fizzbuzz" time="0.000" timestamp="2018-10-18T15:56:30"/>
	<testcase classname="fizzbuzz_tests.fizzBuzzTest" name="test_if_3_is_fizz" time="0.000" timestamp="2018-10-18T15:56:30"/>
	<testcase classname="fizzbuzz_tests.fizzBuzzTest" name="test_if_4_is_4" time="0.000" timestamp="2018-10-18T15:56:30"/>
	<testcase classname="fizzbuzz_tests.fizzBuzzTest" name="test_if_5_is_buzz" time="0.000" timestamp="2018-10-18T15:56:30"/>
	<testcase classname="fizzbuzz_tests.fizzBuzzTest" name="test_if_9_is_fizz" time="0.000" timestamp="2018-10-18T15:56:30"/>
	<testcase classname="fizzbuzz_tests.fizzBuzzTest" name="test_if_fizbuzz_list_contains_start_to_end" time="0.000" timestamp="2018-10-18T15:56:30"/>
	<testcase classname="fizzbuzz_tests.fizzBuzzTest" name="test_if_fizbuzz_list_is_reversable" time="0.000" timestamp="2018-10-18T15:56:30"/>
	<testcase classname="fizzbuzz_tests.fizzBuzzTest" name="test_if_fizzMyBuzz_returns_correct_format" time="0.000" timestamp="2018-10-18T15:56:30"/>
	<testcase classname="fizzbuzz_tests.fizzBuzzTest" name="test_if_fizzbuzz_list_is_converted_to_fizzbuzz" time="0.000" timestamp="2018-10-18T15:56:30"/>
	<testcase classname="fizzbuzz_tests.fizzBuzzTest" name="test_if_fizzbuzz_list_is_initialized" time="0.000" timestamp="2018-10-18T15:56:30"/>
	<testcase classname="fizzbuzz_tests.fizzBuzzTest" name="test_if_fizzbuzz_list_raises_end_exception" time="0.000" timestamp="2018-10-18T15:56:30"/>
	<testcase classname="fizzbuzz_tests.fizzBuzzTest" name="test_if_fizzbuzz_list_raises_start_exception" time="0.000" timestamp="2018-10-18T15:56:30"/>
	<testcase classname="fizzbuzz_tests.fizzBuzzTest" name="test_if_fizzbuzz_returns_a_string" time="0.000" timestamp="2018-10-18T15:56:30"/>
	<testcase classname="fizzbuzz_tests.fizzBuzzTest" name="test_if_fizzbuzz_start_sets" time="0.000" timestamp="2018-10-18T15:56:30"/>
	<testcase classname="fizzbuzz_tests.fizzBuzzTest" name="test_if_makeFizzBuzz_returns_empty_list" time="0.000" timestamp="2018-10-18T15:56:30"/>
	<testcase classname="fizzbuzz_tests.fizzBuzzTest" name="test_if_fizzMyBuzz_raises_start_exception" time="0.002" timestamp="2018-10-18T15:56:30">
		<error message="no start value given" type="Exception">
<![CDATA[Traceback (most recent call last):
  File "/Users/mikebmc/Documents/job_hunting_2018/applications/Intersection/nr_real_fizzbuzz/src/unittest/python/fizzbuzz_tests.py", line 106, in test_if_fizzMyBuzz_raises_start_exception
    fizzbuzz.fizzMyBuzz(None,20)
  File "/Users/mikebmc/Documents/job_hunting_2018/applications/Intersection/nr_real_fizzbuzz/src/main/python/fizzbuzz.py", line 47, in fizzMyBuzz
    raise Exception("no start value given")
Exception: no start value given
]]>		</error>
	</testcase>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
